import {fishingMovement} from '../src/utils/fishing';
import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';

test('provider persists fishing, prevents duplicate rewards, crafts caught fish and blocks combat casting',async()=>{
 const bundle=await build({stdin:{contents:`import React,{act} from 'react';import {createRoot} from 'react-dom/client';import {GameProvider,useGame} from './src/context/GameContext';function Probe(){window.game=useGame();return null;}window.act=act;window.mount=()=>{window.root=createRoot(document.getElementById('root'));window.root.render(<GameProvider><Probe/></GameProvider>);};`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,write:false,platform:'browser',format:'iife',define:{'process.env.NODE_ENV':'"development"','import.meta.env.VITE_ADMIN_TELEGRAM_ID':'""'},plugins:[{name:'art',setup(b){b.onLoad({filter:/\.(jpg|webp)$/},()=>({contents:'export default "art";',loader:'js'}));}}]});
 const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost',runScripts:'outside-only'});const w:any=dom.window;w.MessageChannel=class{port1={onmessage:null as any};port2={postMessage:()=>setTimeout(()=>this.port1.onmessage?.(),0)}};w.IS_REACT_ACT_ENVIRONMENT=true;w.Headers=Headers;w.fetch=async()=>({ok:true,status:200,text:async()=>JSON.stringify({active:false,items:[],ok:true})});w.eval(bundle.outputFiles[0].text);
 try{
  await w.act(async()=>w.mount());await w.act(async()=>w.game.createCharacter('Рыболов','warrior'));w.Math.random=()=>.5;const base=w.game.combatStats;
  const reel=async()=>{for(let n=0;n<26;n++){const c=w.game.player.fishing.cast,f=c.fight;if(f.progress>=100)break;assert(!f.lost);const m=fishingMovement(c);const a=f.tension>=65?'slack':m.mood==='rush'&&f.tension>25&&f.energy>15?'brace':'pull';const time=c.biteAt+(f.step+1)*600;w.Date.now=()=>time;await w.act(async()=>{const r=w.game.fishingAction(a,c.id,f.step);assert(r.success);const stale=w.game.fishingAction(a,c.id,f.step);assert(!stale.success);});}assert.equal(w.game.player.fishing.cast.fight.progress,100);};
  let first:any,duplicate:any;
  await w.act(async()=>{first=w.game.fishingAction('cast','river');duplicate=w.game.fishingAction('cast','river');});assert(first.success);assert(!duplicate.success);assert.equal(w.game.player.stamina,96);assert.equal(w.game.combatStats.attack,base.attack);assert.equal(w.game.combatStats.defense,base.defense);
  let c=w.game.player.fishing.cast;w.Date.now=()=>c.biteAt;await w.act(async()=>w.game.fishingAction('hook',c.id));assert(w.game.player.fishing.cast.hookedAt);
  const seed=JSON.parse(w.localStorage.getItem('aethelgard_save_v1_data'));assert(seed.player.fishing.cast.hookedAt);await w.act(async()=>w.root.unmount());await w.act(async()=>w.mount());assert.equal(w.game.player.fishing.cast.id,c.id);w.Date.now=()=>c.biteAt+1200;
  await reel();await w.act(async()=>{first=w.game.fishingAction('land',c.id);duplicate=w.game.fishingAction('land',c.id);});assert(first.success);assert(!duplicate.success);assert.equal(w.game.player.fishing.catches,1);
  await w.act(async()=>w.game.fishingAction('cast','river'));c=w.game.player.fishing.cast;w.Date.now=()=>c.biteAt;await w.act(async()=>w.game.fishingAction('hook',c.id));w.Date.now=()=>c.biteAt+1200;await reel();await w.act(async()=>w.game.fishingAction('land',c.id));assert.equal(w.game.player.inventory.find((i:any)=>i.templateId==='fish_perch').stackCount,2);
  const copper=w.game.player.inventory.reduce((n:number,i:any)=>n+(i.name==='Медная руда'?(i.stackCount||1):0),0);assert(copper>=1);await w.act(async()=>{first=w.game.craftAlchemy('alc_fish_water');});assert(first);assert(!w.game.player.inventory.some((i:any)=>i.templateId==='fish_perch'));const potion=w.game.player.inventory.find((i:any)=>i.templateId==='alc_fish_water');assert.equal(potion.stats.heal,120);assert.equal(potion.stats.manaRestore,60);assert.equal(w.game.player.fishing.catches,2);
  const target={id:'test',name:'Цель',regionId:'arena',level:1,hp:1000,maxHp:1000,mp:0,maxMp:0,attack:1,magicAttack:0,defense:0,magicDefense:0,speed:1,critChance:0,evasion:0,avatar:'',expReward:1,goldReward:1,drops:[]};await w.act(async()=>w.game.startBattleWithMonster(target,{chain:false,energyCost:0}));await w.act(async()=>{first=w.game.fishingAction('cast','river');});assert(!first.success);
 }finally{await w.act(async()=>w.root.unmount());dom.window.close();}
});
