import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
import fs from 'node:fs/promises';
test('selected interface import failure shows a localized retry screen without evaluating other interfaces',async()=>{
 const bundle=await build({stdin:{contents:`import React,{act}from'react';import{createRoot}from'react-dom/client';import App from'./src/App';window.act=act;window.mount=()=>{window.root=createRoot(document.getElementById('root'));window.root.render(<App/>);};`,resolveDir:process.cwd(),loader:'tsx'},loader:{'.css':'empty'},bundle:true,write:false,platform:'browser',format:'iife',define:{'process.env.NODE_ENV':'"development"','import.meta.env.VITE_ADMIN_TELEGRAM_ID':'""'},plugins:[{name:'failure',setup(b){b.onLoad({filter:/interfaces\/modern\/entry\.tsx$/},()=>({contents:'throw new Error("Connection lost"); export default function Interface(){return null;}',loader:'tsx'}));b.onLoad({filter:/interfaces\/(fantasy|fantasy-beta)\/entry\.tsx$/},()=>({contents:'window.foreignLoaded=true;export default function Interface(){return null;}',loader:'tsx'}));b.onLoad({filter:/InterfaceLoader\.tsx$/},async args=>({contents:(await fs.readFile(args.path,'utf8')).replace('window.location.reload()','(window as any).reloads++'),loader:'tsx'}));b.onLoad({filter:/\.(jpg|webp)$/},()=>({contents:'export default "art";',loader:'js'}));}}]});
 const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost',runScripts:'outside-only'}),w:any=dom.window;
 w.MessageChannel=class{port1={onmessage:null as any};port2={postMessage:()=>setTimeout(()=>this.port1.onmessage?.(),0)}};w.IS_REACT_ACT_ENVIRONMENT=true;w.Headers=Headers;w.AbortSignal=AbortSignal;w.reloads=0;w.console.error=()=>{};w.localStorage.setItem('aethelgard_language','uk');w.fetch=async()=>({ok:true,status:200,text:async()=>'{"resetVersion":0}'});w.eval(bundle.outputFiles[0].text);
 try{await w.act(async()=>w.mount());await w.act(async()=>await new Promise(r=>setTimeout(r,30)));assert.match(w.document.querySelector('[role="alert"]').textContent,/Не вдалося завантажити інтерфейс/);assert.equal(w.foreignLoaded,undefined);await w.act(async()=>w.document.querySelector('button').click());assert.equal(w.reloads,1);}finally{await w.act(async()=>w.root.unmount());dom.window.close();}
});
