export const STAT_LABELS: Record<string, string> = {
  heal: 'Лечение HP',
  manaRestore: 'Восстановление MP',
  attackPercent: 'Усиление атаки, %',
  defensePercent: 'Усиление защиты, %',
  buffDuration: 'Длительность, ходов',
  healFull: 'Полное лечение',
  invulnerable: 'Неуязвимость',
  attack: 'Атака',
  magicAttack: 'Магическая атака',
  defense: 'Защита',
  magicDefense: 'Магическая защита',
  maxHp: 'Макс. HP',
  maxMp: 'Макс. MP',
  speed: 'Скорость',
  accuracy: 'Точность',
  evasion: 'Уклонение',
  critChance: 'Шанс крита',
  critDamage: 'Сила крита',
  vampirism: 'Вампиризм',
  hpRegen: 'Реген. HP',
  mpRegen: 'Реген. MP',
  armorPenetration: 'Пробитие брони',
  physicalResistance: 'Сопр. физике',
  magicResistance: 'Сопр. магии',
  fireResistance: 'Сопр. огню',
  iceResistance: 'Сопр. льду',
  lightningResistance: 'Сопр. молнии',
  poisonResistance: 'Сопр. яду',
  darkResistance: 'Сопр. тьме',
  holyResistance: 'Сопр. свету'
};
