import { t as localize, useLocale, intlLocale } from '../../i18n/locale';
import React,{useState} from 'react';
import {useGame} from '../../context/GameContext';
import {ASCENSION_FRAGMENT_DESCRIPTION,ASCENSION_ECHOES,ascensionWeek,ascensionSeason,ASCENSION_RANKS,ASCENSION_STAGES,nextAscensionStage,passiveChoices,ascensionBonuses,ascensionSkills,fragmentCount,type AscensionPath} from '../../data/ascension';

export const AscensionArena:React.FC<{onEnterCombatTab?:()=>void}>=({onEnterCombatTab})=>{
  useLocale();
 const {player,challengeAscension,ascend,isInCombat,isCombatEnded,activeDungeonRun}=useGame();
 const [choice,setChoice]=useState<AscensionPath|undefined>();const [feedback,setFeedback]=useState('');const [confirm,setConfirm]=useState(false);
 if(!player)return null;
 const state=player.ascension||{rank:'E' as const,trialsWon:[]};const stage=nextAscensionStage(state);const won=Boolean(stage&&state.trialsWon.includes(stage.rank));const choices=passiveChoices(player.classId);const bonus=ascensionBonuses(state);
 const choiceRequired=stage?.rank==='D'||stage?.rank==='A';const fragments=fragmentCount(player);const occupied=isInCombat&&!isCombatEnded||Boolean(activeDungeonRun);
 const ready=Boolean(stage&&won&&player.silver>=stage.silver&&fragments>=stage.fragments&&(!choiceRequired||choice)&&!occupied);
 const requirements=stage?[
  !won?'Победите хранителя.':null,
  choiceRequired&&!choice?'Выберите пассивку выше.':null,
  player.silver<stage.silver?`Не хватает ${stage.silver-player.silver} серебра.`:null,
  fragments<stage.fragments?`Не хватает ${stage.fragments-fragments} осколков вознесения.`:null,
  occupied?'Завершите текущий бой или подземелье.':null,
 ].filter(Boolean):[];
 return <div className="space-y-3">
  <section className="ui-panel rounded-xl border p-4 space-y-3"><h2 className="font-cinzel text-base font-bold text-amber-200">{localize("Арена вознесения")}</h2><p className="text-xs text-slate-400">{localize("Уровень ")}{localize(player.level)}{localize(" · Ранг вознесения ")}<b className="text-amber-200">{localize(state.rank)}</b></p><p className="text-xs text-slate-400">{localize("Победите хранителя следующего ранга, подготовьте материалы и вознеситесь. Уровень, опыт, экипировка и вложенные таланты сохраняются.")}</p><div className="flex flex-wrap gap-2">{ASCENSION_RANKS.map(rank=><span key={rank} className={`rounded border px-2 py-1 text-xs ${rank===state.rank?'border-amber-400 bg-amber-950 text-amber-200':ASCENSION_RANKS.indexOf(rank)<ASCENSION_RANKS.indexOf(state.rank)?'text-emerald-300 border-emerald-900':'text-slate-500 border-slate-800'}`}>{localize(rank)}</span>)}</div></section>
  {stage?<section className="rounded-xl border border-slate-700 p-4 space-y-3 bg-slate-950"><h3 className="text-sm text-amber-100">{localize("Испытание ")}{localize(state.rank)} → {localize(stage.rank)}: {localize(stage.name)}</h3><p className="text-xs text-slate-400">{localize(stage.hint)}</p><p className="text-xs text-slate-400">HP {localize(stage.hp.toLocaleString(intlLocale()))}{localize(" · атака ")}{localize(stage.power)}{localize(" · защита ")}{localize(stage.defense)}{localize(". Сила хранителя фиксирована для ранга.")}</p><p className="text-xs text-emerald-300">{localize("Подготовка: герой примерно ")}{localize(stage.recommendedLevel)}{localize(" ур., комплект +")}{localize(stage.recommendedUpgrade)}{localize(". Первое вознесение доступно без осколков и предыдущих бонусов.")}</p><p className="text-xs text-cyan-200">{localize("Откроется: ")}{localize(stage.reward)}.</p><p className="text-xs text-slate-400">{localize(won?'✅ Хранитель побеждён. Победа сохранена.':`🎟️ Одна попытка — 1 билет арены. Доступно: ${player.arenaTickets}.`)}{localize(" За испытание не начисляются опыт, золото или рейтинг.")}</p>
   {!won&&<button disabled={occupied||player.arenaTickets<1} onClick={()=>{const result=challengeAscension();setFeedback(result.message);if(result.success)onEnterCombatTab?.();}} className="w-full rounded-lg bg-amber-700 py-3 text-sm font-bold disabled:opacity-40">{localize("Вызвать хранителя ")}{localize(stage.rank)}</button>}
   <div className="rounded-lg border border-slate-800 p-3 text-xs space-y-1"><p>{localize("Серебро: ")}{localize(player.silver.toLocaleString(intlLocale()))} / {localize(stage.silver.toLocaleString(intlLocale()))}</p><p>{localize("Осколки вознесения: ")}{localize(fragments)} / {localize(stage.fragments)}</p><p className="text-slate-500">{localize(ASCENSION_FRAGMENT_DESCRIPTION)}{localize(" Запертые и клановые осколки не расходуются.")}</p></div>
   {choiceRequired&&<fieldset className="space-y-2"><legend className="text-xs text-slate-300 mb-2">{localize("Выберите ")}{localize(stage.rank==='D'?'первую':'вторую')}{localize(" пассивку")}</legend>{choices.filter(p=>stage.rank!=='A'||p.id!==state.primary).map(p=><label key={p.id} className={`block rounded-lg border p-2 text-xs ${choice===p.id?'border-cyan-500 bg-cyan-950/20':'border-slate-800'}`}><input type="radio" name="ascension-path" checked={choice===p.id} onChange={()=>setChoice(p.id)}/><b className="ml-2">{localize(p.name)}</b><p className="mt-1 text-slate-400">{localize(p.description)}</p></label>)}</fieldset>}
   <p role="status" className="text-xs text-amber-200">{localize(ready?'Всё готово. Нажмите «Вознестись» и подтвердите переход.':requirements.map(localize).join(' '))}</p>
   <button disabled={!ready} onClick={()=>setConfirm(true)} className="w-full rounded-lg bg-cyan-700 py-3 text-sm font-bold disabled:opacity-40">{localize("Вознестись до ")}{localize(stage.rank)}</button>
  </section>:<section className="rounded-xl border border-amber-600 p-4 text-sm text-amber-200">{localize("🌟 Достигнут высший ранг SSS. Все этапы вознесения завершены.")}</section>}
  {state.rank==='SSS'&&<section className="rounded-xl border border-purple-800 p-3 space-y-3"><h3 className="text-sm font-bold text-purple-200">{localize("Эхо хранителей · эндгейм")}</h3><p className="text-xs text-slate-400">{localize("За каждое эхо: 3000 серебра и сезонная победа, один раз в неделю. Полная тройка открывает памятный титул. Новая неделя — понедельник, 00:00 UTC.")}</p><p className="text-xs text-amber-200">{localize("Сезон ")}{localize(ascensionSeason())}: {localize(state.season===ascensionSeason()?state.seasonWins||0:0)}{localize(" побед")}</p>{ASCENSION_ECHOES.map(echo=><div key={echo.id} className="rounded border border-slate-800 p-2 text-xs"><b>{localize(echo.name)}</b><p className="text-slate-400 mt-1">{localize(echo.hint)}</p><button disabled={occupied||player.arenaTickets<1||state.echoWeek===ascensionWeek()&&state.echoWins?.includes(echo.id)} onClick={()=>{const result=challengeAscension(echo.id);setFeedback(result.message);if(result.success)onEnterCombatTab?.();}} className="mt-2 rounded bg-purple-900 px-3 py-2 disabled:opacity-40">{localize(state.echoWeek===ascensionWeek()&&state.echoWins?.includes(echo.id)?'Пройдено на этой неделе':'Испытать себя · 1 билет')}</button></div>)}{state.titles?.map(title=><p key={title} className="text-xs text-amber-200">🏅 {localize(title)}</p>)}</section>}
  {state.primary&&<section className="rounded-xl border border-slate-800 p-3 space-y-2"><h3 className="text-xs font-bold text-cyan-200">{localize("Пассивки вознесения")}</h3>{[state.primary,state.secondary].filter(Boolean).map(path=><div key={path} className="text-xs text-slate-300"><b>{localize(choices.find(p=>p.id===path)?.name)}</b><p className="text-slate-400">{localize(path==='precision'?`+${bonus.afflictedDamage}% урона по ослабленной цели`:path==='ward'?`Защита восстанавливает ${bonus.defendHeal}% максимального HP`:`Навык возвращает ${bonus.manaReturn}% потраченной маны`)}</p></div>)}{bonus.synergy&&<p className="text-xs text-emerald-300">{localize("Сочетание SS: новые навыки вознесения восстанавливают 2% HP и получают +2% урона.")}</p>}</section>}
  {ascensionSkills(player.classId,state).length>0&&<section className="rounded-xl border border-slate-800 p-3 space-y-2"><h3 className="text-xs font-bold text-cyan-200">{localize("Новые навыки")}</h3>{ascensionSkills(player.classId,state).map(skill=><div key={skill.id} className="text-xs"><b>{localize(skill.icon)} {localize(skill.name)}</b><p className="text-slate-400">{localize(skill.description)} · {localize(skill.manaCost)} MP</p></div>)}</section>}
  <details className="rounded-xl border border-slate-800 p-3 text-xs"><summary>{localize("Все хранители и награды")}</summary>{ASCENSION_STAGES.map(s=><p key={s.rank} className="mt-2 text-slate-400"><b>{localize(s.rank)}: {localize(s.name)}</b> — {localize(s.reward)}.</p>)}</details>
  {feedback&&<p role="status" className="rounded-lg bg-slate-900 p-3 text-xs text-amber-200">{localize(feedback)}</p>}
  {confirm&&stage&&<div className="fixed inset-0 z-50 bg-black/80 flex items-center justify-center p-4"><div role="dialog" aria-modal="true" aria-label={localize("Подтверждение вознесения")} className="max-w-md w-full rounded-xl border border-cyan-700 bg-slate-950 p-4 space-y-3"><h3 className="text-sm font-bold text-cyan-200">{localize("Вознесение до ")}{localize(stage.rank)}</h3><p className="text-xs text-slate-300">{localize("Будет потрачено ")}{localize(stage.silver.toLocaleString(intlLocale()))}{localize(" серебра и ")}{localize(stage.fragments)}{localize(" осколков. ")}{localize(choiceRequired?`Выбор: ${choices.find(p=>p.id===choice)?.name}.`:stage.reward)}{localize(" Уровень и текущее снаряжение сохраняются.")}</p><div className="flex gap-2"><button onClick={()=>setConfirm(false)} className="flex-1 rounded bg-slate-800 p-2 text-xs">{localize("Отмена")}</button><button disabled={!ready} onClick={()=>{const result=ascend(choice);setFeedback(result.message);setConfirm(false);if(result.success)setChoice(undefined);}} className="flex-1 rounded bg-cyan-700 p-2 text-xs disabled:opacity-40">{localize("Подтвердить вознесение")}</button></div></div></div>}
 </div>;
};
