import React,{useState} from 'react';
import {useGame} from '../../../../context/GameContext';
import {ASCENSION_FRAGMENT_DESCRIPTION,ASCENSION_ECHOES,ascensionWeek,ascensionSeason,ASCENSION_RANKS,ASCENSION_STAGES,nextAscensionStage,passiveChoices,ascensionBonuses,ascensionSkills,fragmentCount,type AscensionPath} from '../../../../data/ascension';
import { RpgIcon } from '../ui/RpgIcon';
import { BestiaryPanel, RpgButton } from '../ui/BestiaryUI';

export const AscensionArena:React.FC<{onEnterCombatTab?:()=>void}>=({onEnterCombatTab})=>{
 const {player,challengeAscension,ascend,isInCombat,isCombatEnded,activeDungeonRun}=useGame();
 const [choice,setChoice]=useState<AscensionPath|undefined>();const [feedback,setFeedback]=useState('');const [confirm,setConfirm]=useState(false);
 if(!player)return null;
 const state=player.ascension||{rank:'E' as const,trialsWon:[]};const stage=nextAscensionStage(state);const won=Boolean(stage&&state.trialsWon.includes(stage.rank));const choices=passiveChoices(player.classId);const bonus=ascensionBonuses(state);
 const choiceRequired=stage?.rank==='D'||stage?.rank==='A';const fragments=fragmentCount(player);const occupied=isInCombat&&!isCombatEnded||Boolean(activeDungeonRun);
 const ready=Boolean(stage&&won&&player.silver>=stage.silver&&fragments>=stage.fragments&&(!choiceRequired||choice)&&!occupied);
 const requirements=stage?[
  !won?'Победите хранителя.':null,
  choiceRequired&&!choice?'Выберите пассивку выше.':null,
  player.silver<stage.silver?`Не хватает ${stage.silver-player.silver} серебра.`:null,
  fragments<stage.fragments?`Не хватает ${stage.fragments-fragments} осколков вознесения.`:null,
  occupied?'Завершите текущий бой или подземелье.':null,
 ].filter(Boolean):[];
 return <div className="space-y-3">
  <BestiaryPanel className="space-y-3 p-3"><h2 className="font-cinzel text-base font-bold text-amber-200">Арена вознесения</h2><p className="text-xs text-slate-400">Уровень {player.level} · Ранг вознесения <b className="text-amber-200">{state.rank}</b></p><p className="text-xs text-slate-400">Победите хранителя следующего ранга, подготовьте материалы и вознеситесь. Уровень, опыт, экипировка и вложенные таланты сохраняются.</p><div className="flex flex-wrap gap-2">{ASCENSION_RANKS.map(rank=><span key={rank} className={`rounded border px-2 py-1 text-xs ${rank===state.rank?'border-amber-400 bg-amber-950 text-amber-200':ASCENSION_RANKS.indexOf(rank)<ASCENSION_RANKS.indexOf(state.rank)?'text-emerald-300 border-emerald-900':'text-slate-500 border-slate-800'}`}>{rank}</span>)}</div></BestiaryPanel>
  {stage?<BestiaryPanel className="space-y-3 p-3"><h3 className="text-sm text-amber-100">Испытание {state.rank} → {stage.rank}: {stage.name}</h3><p className="text-xs text-slate-400">{stage.hint}</p><p className="text-xs text-slate-400">HP {stage.hp.toLocaleString()} · атака {stage.power} · защита {stage.defense}. Сила хранителя фиксирована для ранга.</p><p className="text-xs text-emerald-300">Подготовка: герой примерно {stage.recommendedLevel} ур., комплект +{stage.recommendedUpgrade}. Первое вознесение доступно без осколков и предыдущих бонусов.</p><p className="text-xs text-cyan-200">Откроется: {stage.reward}.</p><p className="text-xs text-slate-400">{won?'Хранитель побеждён. Победа сохранена.':`Одна попытка — 1 билет арены. Доступно: ${player.arenaTickets}.`} За испытание не начисляются опыт, золото или рейтинг.</p>
   {!won&&<RpgButton variant="primary" icon="arena" disabled={occupied||player.arenaTickets<1} onClick={()=>{const result=challengeAscension();setFeedback(result.message);if(result.success)onEnterCombatTab?.();}} className="w-full">Вызвать хранителя {stage.rank}</RpgButton>}
   <div className="rounded-lg border border-slate-800 p-3 text-xs space-y-1"><p>Серебро: {player.silver.toLocaleString()} / {stage.silver.toLocaleString()}</p><p>Осколки вознесения: {fragments} / {stage.fragments}</p><p className="text-slate-500">{ASCENSION_FRAGMENT_DESCRIPTION} Запертые и клановые осколки не расходуются.</p></div>
   {choiceRequired&&<fieldset className="space-y-2"><legend className="text-xs text-slate-300 mb-2">Выберите {stage.rank==='D'?'первую':'вторую'} пассивку</legend>{choices.filter(p=>stage.rank!=='A'||p.id!==state.primary).map(p=><label key={p.id} className={`block rounded-lg border p-2 text-xs ${choice===p.id?'border-cyan-500 bg-cyan-950/20':'border-slate-800'}`}><input type="radio" name="ascension-path" checked={choice===p.id} onChange={()=>setChoice(p.id)}/><b className="ml-2">{p.name}</b><p className="mt-1 text-slate-400">{p.description}</p></label>)}</fieldset>}
   <p role="status" className="text-xs text-amber-200">{ready?'Всё готово. Нажмите «Вознестись» и подтвердите переход.':requirements.join(' ')}</p>
   <button disabled={!ready} onClick={()=>setConfirm(true)} className="w-full rounded-lg bg-cyan-700 py-3 text-sm font-bold disabled:opacity-40">Вознестись до {stage.rank}</button>
   </BestiaryPanel>:<BestiaryPanel className="p-4 text-sm text-amber-200">Достигнут высший ранг SSS. Все этапы вознесения завершены.</BestiaryPanel>}
  {state.rank==='SSS'&&<BestiaryPanel className="space-y-3 p-3"><h3 className="text-sm font-bold text-purple-200">Эхо хранителей · эндгейм</h3><p className="text-xs text-slate-400">За каждое эхо: 3000 серебра и сезонная победа, один раз в неделю. Полная тройка открывает памятный титул. Новая неделя — понедельник, 00:00 UTC.</p><p className="text-xs text-amber-200">Сезон {ascensionSeason()}: {state.season===ascensionSeason()?state.seasonWins||0:0} побед</p>{ASCENSION_ECHOES.map(echo=><div key={echo.id} className="leather-panel p-2 text-xs"><b>{echo.name}</b><p className="mt-1 text-slate-400">{echo.hint}</p><RpgButton variant="secondary" disabled={occupied||player.arenaTickets<1||state.echoWeek===ascensionWeek()&&state.echoWins?.includes(echo.id)} onClick={()=>{const result=challengeAscension(echo.id);setFeedback(result.message);if(result.success)onEnterCombatTab?.();}} className="mt-2">{state.echoWeek===ascensionWeek()&&state.echoWins?.includes(echo.id)?'Пройдено на этой неделе':'Испытать себя · 1 билет'}</RpgButton></div>)}{state.titles?.map(title=><p key={title} className="text-xs text-amber-200">{title}</p>)}</BestiaryPanel>}
  {state.primary&&<BestiaryPanel className="space-y-2 p-3"><h3 className="text-xs font-bold text-cyan-200">Пассивки вознесения</h3>{[state.primary,state.secondary].filter(Boolean).map(path=><div key={path} className="text-xs text-slate-300"><b>{choices.find(p=>p.id===path)?.name}</b><p className="text-slate-400">{path==='precision'?`+${bonus.afflictedDamage}% урона по ослабленной цели`:path==='ward'?`Защита восстанавливает ${bonus.defendHeal}% максимального HP`:`Навык возвращает ${bonus.manaReturn}% потраченной маны`}</p></div>)}{bonus.synergy&&<p className="text-xs text-emerald-300">Сочетание SS: новые навыки вознесения восстанавливают 2% HP и получают +2% урона.</p>}</BestiaryPanel>}
  {ascensionSkills(player.classId,state).length>0&&<BestiaryPanel className="space-y-2 p-3"><h3 className="text-xs font-bold text-cyan-200">Новые навыки</h3>{ascensionSkills(player.classId,state).map(skill=><div key={skill.id} className="text-xs"><b className="flex items-center gap-2"><RpgIcon kind="skill" size={16}/>{skill.name}</b><p className="text-slate-400">{skill.description} · {skill.manaCost} MP</p></div>)}</BestiaryPanel>}
  <details className="leather-panel p-3 text-xs"><summary className="min-h-11 cursor-pointer py-3">Все хранители и награды</summary>{ASCENSION_STAGES.map(s=><p key={s.rank} className="mt-2 text-slate-400"><b>{s.rank}: {s.name}</b> — {s.reward}.</p>)}</details>
  {feedback&&<p role="status" className="rounded-lg bg-slate-900 p-3 text-xs text-amber-200">{feedback}</p>}
  {confirm&&stage&&<div className="bottom-sheet-backdrop fixed inset-0 z-50 flex items-center justify-center p-4"><div role="dialog" aria-modal="true" aria-label="Подтверждение вознесения" className="dialog-frame w-full max-w-md space-y-3 p-4"><h3 className="section-title text-sm text-cyan-200">Вознесение до {stage.rank}</h3><p className="text-xs text-slate-300">Будет потрачено {stage.silver.toLocaleString()} серебра и {stage.fragments} осколков. {choiceRequired?`Выбор: ${choices.find(p=>p.id===choice)?.name}.`:stage.reward} Уровень и текущее снаряжение сохраняются.</p><div className="flex gap-2"><RpgButton variant="secondary" onClick={()=>setConfirm(false)} className="flex-1">Отмена</RpgButton><RpgButton variant="primary" disabled={!ready} onClick={()=>{const result=ascend(choice);setFeedback(result.message);setConfirm(false);if(result.success)setChoice(undefined);}} className="flex-1">Подтвердить вознесение</RpgButton></div></div></div>}
 </div>;
};
